export const EXACT_REMOVE_SELECTORS: string[] = [
  'script',
  'style',
  'noscript',
  'template',
  'link[rel="preload"]',
  'link[rel="prefetch"]',
  'link[rel="dns-prefetch"]',
  'iframe[src*="doubleclick.net"]',
  'iframe[src*="googlesyndication.com"]',
  'iframe[src*="taboola.com"]',
  'iframe[src*="outbrain.com"]',
  'iframe[src*="adservice"]',
  '[id="ads"]',
  '[class="ads"]',
  '[class*=" ad-"]',
  '[class^="ad-"]',
  '[id^="ad-"]',
  '[id*=" ad-"]',
  '[class*="sponsored"]',
  '[id*="sponsored"]',
  '[data-testid*="ad"]',
  '[aria-label*="advertisement" i]',
  '[role="complementary"]',
  '[data-nosnippet]',
  '.advertisement',
  '.ad-container',
  '.adsbox',
  '.ad-slot',
  '.cookie-banner',
  '.cookie-consent',
  '.consent-banner',
  '.gdpr-banner',
  '[id*="cookie"]',
  '[class*="cookie"]',
  '[id*="consent"]',
  '[class*="consent"]',
  'nav:not(article nav):not(main nav)',
  'header:not(article header):not(main header)',
  'footer:not(article footer):not(main footer)',
  '[role="navigation"]:not(article [role="navigation"]):not(main [role="navigation"])',
  '[class*="navbar"]',
  '[id*="navbar"]',
  '[class*="breadcrumb"]',
  '[aria-label*="breadcrumb" i]',
  '[class*="sidebar"]',
  '[id*="sidebar"]',
  '[class*="side-bar"]',
  '[id*="side-bar"]',
  '[data-testid*="sidebar"]',
  '[class*="social"]',
  '[id*="social"]',
  '[class*="share"]',
  '[id*="share"]',
  '[class*="newsletter"]',
  '[id*="newsletter"]',
  '[class*="subscribe"]',
  '[id*="subscribe"]',
  '[class*="related"]',
  '[id*="related"]',
  '[class*="recommended"]',
  '[id*="recommended"]',
  '[class*="comment"]',
  '[id*="comment"]',
  '#comments',
  '.comments',
  '[class*="disqus"]',
  '[id*="disqus"]',
  '[class*="modal"]',
  '[id*="modal"]',
  '[class*="popup"]',
  '[id*="popup"]',
  '[class*="overlay"]',
  '[id*="overlay"]',
  '[class*="paywall"]',
  '[id*="paywall"]',
  '[class*="signup"]',
  '[id*="signup"]',
  '[class*="banner"]',
  '[id*="banner"]',
  '[class*="promo"]',
  '[id*="promo"]',
  '[class*="widget"]',
  '[id*="widget"]',
  '[class*="outbrain"]',
  '[id*="outbrain"]',
  '[class*="taboola"]',
  '[id*="taboola"]',
  '[class*="pagination"]',
  '[id*="pagination"]',
  '[class*="pager"]',
  '[id*="pager"]',
  '[role="navigation"][aria-label*="pagination" i]',
  '[class*="page-nav"]',
  '[class*="load-more"]',
  '[id*="load-more"]',
  '[hidden]',
  '[inert]',
  '[aria-hidden="true"]',
  '[style*="display:none"]',
  '[style*="visibility:hidden"]',
];

export const PARTIAL_REMOVE_PATTERNS: string[] = [
  'advert',
  'adslot',
  'ad-slot',
  'adunit',
  'ad-unit',
  'adwrapper',
  'ad-wrapper',
  'adsense',
  'sponsor',
  'promoted',
  'promo-',
  '-promo',
  'cookie',
  'consent',
  'gdpr',
  'eu-banner',
  'subscribe',
  'newsletter',
  'mailing',
  'signup',
  'sign-up',
  'register',
  'account-wall',
  'paywall',
  'metered',
  'sidebar',
  'side-bar',
  'rail',
  'left-rail',
  'right-rail',
  'footer-',
  '-footer',
  'site-footer',
  'page-footer',
  'header-',
  '-header',
  'site-header',
  'global-nav',
  'navigation',
  'nav-',
  'breadcrumb',
  'related',
  'recommended',
  'popular-post',
  'trending',
  'comment',
  'discussion',
  'reply',
  'share',
  'social',
  'follow-us',
  'author-box',
  'bio-box',
  'widget',
  'module-',
  'carousel',
  'slider',
  'modal',
  'popup',
  'overlay',
  'lightbox',
  'toast',
  'notification',
  'interstitial',
  'tracking',
  'analytics',
  'pixel',
  'pagination',
  'pager',
  'page-nav',
  'load-more',
  'show-more',
];

export const PRESERVE_RULES: string[] = [
  'article',
  'main',
  '[role="main"]',
  '[itemprop="articleBody"]',
  '.post-content',
  '.entry-content',
  '.article-content',
  '.content-body',
  '.story-body',
  '.article-body',
  '.prose',
  'img',
  'picture',
  'source',
  'figure',
  'figcaption',
  'pre',
  'code',
  'table',
  'thead',
  'tbody',
  'tr',
  'td',
  'th',
  'blockquote',
  'canvas',
  'math',
  'video',
  'audio',
  'iframe[src*="player.vimeo.com"]',
  'iframe[src*="youtube.com"]',
  'iframe[src*="youtu.be"]',
  'iframe[src*="youtube-nocookie.com"]',
  'iframe[src*="vimeo.com"]',
  'iframe[src*="archive.org"]',
  'iframe[src*="wikimedia.org"]',
  'iframe[title*="video" i]',
  'iframe[role="img"]',
  'svg[role="img"]',
  'svg[aria-label]',
  'svg[aria-labelledby]',
  'details',
  'summary',
];

export const BOILERPLATE_PHRASES: RegExp[] = [
  /\ball rights reserved\b/i,
  /\bcopyright\b/i,
  /\bprivacy policy\b/i,
  /\bterms of (service|use)\b/i,
  /\bcookie policy\b/i,
  /\bmanage (consent|preferences)\b/i,
  /\bsubscribe( now)?\b/i,
  /\bsign up (for|to)\b/i,
  /\bjoin our newsletter\b/i,
  /\bnewsletter\b/i,
  /\bfollow us\b/i,
  /\bshare (this|article|post)\b/i,
  /\bshare on\b/i,
  /\bread more\b/i,
  /\brelated (articles|posts|content)\b/i,
  /\brecommended (for you|articles|stories)\b/i,
  /\bmost (popular|read)\b/i,
  /\badvertisement\b/i,
  /\bsponsored\b/i,
  /\bpromoted\b/i,
  /\bclick here\b/i,
  /\bopen in (new tab|app)\b/i,
  /\bdownload our app\b/i,
  /\bback to top\b/i,
  /\bleave a comment\b/i,
  /\bcomments?\b/i,
  /\baccept (all )?cookies\b/i,
  /\bdo not sell my personal information\b/i,
  /\bthis site uses cookies\b/i,
  /\bcontact us\b/i,
  /\bmore stories\b/i,
  /\bmore coverage\b/i,
  /\b(previous|next)\s*page\b/i,
  /\bpage \d+ of \d+\b/i,
  /\bload more\b/i,
  /\bshow more\b/i,
  /\bskip to\b/i,
  /\btop stories\b/i,
  /\btrending now\b/i,
  /\beditor'?s picks?\b/i,
];
